# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sum it!
description: A bookmarklet to quickly sum data

# Build settings
markdown: kramdown
remote_theme: pages-themes/architect
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
exclude:
  - build
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - node_modules
  - README.md
  - src
  - package-lock.json
  - package.json
  - vagrant
  - Vagrantfile

# Server settings
port: 80
host: 0.0.0.0 # listen on all interfaces (not only loopback) so it's accessible outside the VM
              # see: https://zarino.co.uk/post/jekyll-local-network/
              #      https://stackoverflow.com/a/16608698)
